### ISSUE TITLE
How to use ExternalProject_Add()?

### ISSUE THREAD

**Issue by rcdailey** [Orphis/boost-cmake#41]
I'd like to use `ExternalProject_Add()` instead of building boost projects with my other targets. The reason is due to build times but also I do not want 'clean' commands to cause boost to rebuild. Also the boost projects create clutter in Visual Studio solution explorer and slow down indexing/project load times.

I think to get external project working, I need an INSTALL target. Doesn't seem you have one defined. Should one be implemented or do you have any other advice for building this way?

**Comment by Orphis** [comment]
Hi Robert,

From experience, rebuilding Boost doesn't take much time if you only build your top level targets, like 10s total for my project.
Building the whole solution will probably take more time because of some slow to build libraries. If you can't get away from "build whole solution", I may add some way to filter which Boost library will be built, so you only get what you use, and would hopefully be a small enough subset.

As for ExternalProject_Add, I believe this is a hack and shouldn't be used. It doesn't forward all the build flags properly to the subproject from the main project and is error prone. I don't believe you need to have install targets if you insist on using it though. But with install targets and export module it would certainly be easier.

Would you be alright testing if the first solution is satisfactory? Without changing the code, you could just set the variable BOOST_LIBS as a cache variable with the libraries you want before doing your `add_subdirectory()` call.

**Comment by rcdailey** [comment]
Well the big downside to ExternalProject (for me, at least) is that it builds at runtime and you can't set up dependencies. I guess I'll give your suggestion a shot (using `BOOST_LIBS`).

**Comment by Orphis** [comment]
Yes, that is indeed another problem. You could in theory setup some imported targets that depend on the external project and point to the build artifact in it, but it's just another layer of hacks...
Straightforward CMake is better.

Also, to reduce your build times, you could use the Ninja generator maybe with sccache on Windows, it will cache build artifacts and should speedup quite significantly your builds. I know with the latest Visual Studio 15.3, it will be supported directly with their CMake integration, which is quite nice. The only issue is that it changes the workflow in Visual Studio from project based to folder based, which might be a big issue sometimes.

**Comment by rcdailey** [comment]
By the way I'm not able to override `BOOST_LIBS` because it always sets the list and local variables take precedence over cache variables in CMake. I made the following change which fixes it:

```
if(NOT BOOST_LIBS)
  set(BOOST_LIBS
    # Compiled libs
    atomic
    chrono
    container
    context
    coroutine
    date_time
    exception
    fiber
    filesystem
    graph
    iostreams
    locale
    log
    math
    mpi
    graph_parallel # depends on mpi, so needs to be put after it
    program_options
    #python # complex module
    random
    regex
    serialization
    signals
    system
    unit_test_framework
    thread
    timer
    type_erasure
    wave
  )
endif()

list( APPEND BOOST_LIBS
  # Header only libs
  header
)
```

Do you want a PR?

**Comment by Orphis** [comment]
Local variables are overriding cache variables? I didn't know that!
I'm thinking of doing it a little bit differently as I will be probably adding more header only libraries at some point (like asio, which needs a dependency on OpenSSL). I have a hacking day tomorrow planned, so I'll probably do it then :)

**Comment by Orphis** [comment]
Also, a problem with the code above is that if BOOST_LIBS is intentionally empty (maybe you just want header only libraries), you'll end up with the full list defined.

**Comment by rcdailey** [comment]
Hmm yeah, true. Anyway this works for me for the moment. I'll keep this on my fork until you get a more appropriate solution in place. At the moment I don't plan to specify an empty list so non-issue for me.
