### ISSUE TITLE
Boost v1.69.0

### ISSUE THREAD

**Issue by macdew** [Orphis/boost-cmake#65]
I notice that Boost 1.69.0 is out.  A few build changes are apparent browsing the release notes.  System library is now header-only, and eg boost::filesystem has dropped its dependency on system.  Signals library has been removed...

This probably requires a number of small tweaks to our boost-cmake scripts...

**Comment by Orphis** [comment]
Actually, it just works out of the box. There is still some compatibility  library left for boost::system, which is probably a good idea not to break anyones build. I could still remove the dependency internally on it and leave a shim library.

As for signals, since we check if each library has a matching folder in the build source tree  and this one doesn't, it is simply ignored :)

I'll try to finish the Azure Pipelines work first before sending a new version, but it should come soon!

**Comment by Orphis** [comment]
Done with #67
